### ISSUE TITLE
name on segment cannot be None

### ISSUE THREAD

**Issue by lepmik** [OpenElectrophy/OpenElectrophy#10]
Hi, I accidentally got name=None in segment which lead to an error when reading data:

```
startOpenElectrophy.py 
OE3 with neo0.4 : Experimentale!!!
/home/mikkel/.virtualenvs/NEO/local/lib/python2.7/site-packages/guidata/utils.py:25: ImportWarning: Not importing directory '/home/mikkel/.virtualenvs/NEO/local/lib/python2.7/site-packages/guidata/locale': missing __init__.py
  import locale # Warning: 2to3 false alarm ('import' fixer)
no imageio
Traceback (most recent call last):
  File "/home/mikkel/apps/NEO/OpenElectrophy/OpenElectrophy/gui/importdata.py", line 211, in startImporting
    read_and_import(name, self.ioclass,io_kargs, self.dbinfo, options)
  File "/home/mikkel/apps/NEO/OpenElectrophy/OpenElectrophy/gui/importdata.py", line 292, in read_and_import
    session.commit()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 776, in commit
    self.transaction.commit()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 377, in commit
    self._prepare_impl()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 357, in _prepare_impl
    self.session.flush()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1919, in flush
    self._flush(objects)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2037, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2001, in _flush
    flush_context.execute()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 526, in execute
    uow
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 65, in save_obj
    mapper, table, insert)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 602, in _emit_insert_statements
    execute(statement, params)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InterfaceError: (InterfaceError) Error binding parameter 3 - probably unsupported type. u'INSERT INTO "Segment" (file_datetime, rec_datetime, "index", name, description, file_origin, block_id) VALUES (?, ?, ?, ?, ?, ?, ?)' (None, None, None, array(['recording_0'], 
      dtype='|S11'), None, u'/home/mikkel/apps/NEO/DATA/test_hybrid_120sec', 1)
Traceback (most recent call last):
  File "/home/mikkel/apps/NEO/OpenElectrophy/OpenElectrophy/gui/importdata.py", line 211, in startImporting
    read_and_import(name, self.ioclass,io_kargs, self.dbinfo, options)
  File "/home/mikkel/apps/NEO/OpenElectrophy/OpenElectrophy/gui/importdata.py", line 292, in read_and_import
    session.commit()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 776, in commit
    self.transaction.commit()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 375, in commit
    self._assert_active(prepared_ok=True)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 214, in _assert_active
    % self._rollback_exception
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (InterfaceError) Error binding parameter 3 - probably unsupported type. u'INSERT INTO "Segment" (file_datetime, rec_datetime, "index", name, description, file_origin, block_id) VALUES (?, ?, ?, ?, ?, ?, ?)' (None, None, None, array(['recording_0'], 
      dtype='|S11'), None, u'/home/mikkel/apps/NEO/DATA/test_hybrid_120sec', 1)
```

**Comment by samuelgarcia** [comment]
I am not sur but I think that name = None is not compliant with neo API 
for IOs.

You should make a simple unitest that is similar to this:
https://github.com/NeuralEnsemble/python-neo/blob/master/neo/test/iotest/test_elphyio.py


Give me some files (small) I put them on the http.
The BaseTestIO download that files and test the compliance of all 
attributes.
If some of them fails you could have trouble using OpenElectrophy.


Samuel

**Comment by lepmik** [comment]
Will do, however at the moment I only have files of around 150 Mb. I can generate small open ephys files but not klustakwik files at the moment. I will test with local files first and notify you when I have smaller versions. Thanks

**Comment by lepmik** [comment]
The tests seem to be fine with name=None

**Comment by lepmik** [comment]
However now I have changed the IO to read block instead of only segment and now name = None is ok. I think there was some issue with having an IO to only read a segment with no recordingchannelgroup!?

**Comment by samuelgarcia** [comment]
OK sorry. Wrong guess so.

If your IO have:
readable_objects   = [ Segment ] 
and so define a read_segment in your IO you can't have :
supported_objects  = [ Segment , AnalogSignal, RecordingChannelGroup]

because RecordingChannelGroup are linked to a Block.

So you have 2 options:
1 - 
readable_objects   = [ Segment ] 
supported_objects  = [ Segment , AnalogSignal]
this a more simple IO to write. In this case OpenElectrophy do populate Block, RecordingChannelGroup, RecordingChannel for you.
2 - 
readable_objects   = [ Block ] 
supported_objects  = [ Block, Segment , RecordingChannelGroup, RecordingChannel, AnalogSignal]
this is mor complicated to write but it is more complete. In this case you can use the 
populate_RecordingChannel(block)
block.create_many_to_one_relationship()
see
https://github.com/NeuralEnsemble/python-neo/blob/master/neo/io/tools.py

**Comment by lepmik** [comment]
thank you very much, now it works fine and the IO passes all tests. However, there should be some tests realizing what I did wrong. I found cases where the tests ran ok but openelectrophy sent an error..
