### ISSUE TITLE
starting OpenElectrophy error

### ISSUE THREAD

**Issue by cchorn** [OpenElectrophy/OpenElectrophy#16]
When running ..
python startOpenElectrophy.py

I get this error ...

ValueError: API 'QString' has already been set to version 1

**Comment by kylerbrown** [comment]
Hi all, 
I have the same issue. Full error message:

````
(openelectrophy)kjbrown@pequod:~$ startOpenElectrophy.py 
/home/kjbrown/miniconda/envs/openelectrophy/lib/python2.7/site-packages/matplotlib/__init__.py:872: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))
Traceback (most recent call last):
  File "/home/kjbrown/miniconda/envs/openelectrophy/bin/startOpenElectrophy.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/kjbrown/projects/OpenElectrophy/startOpenElectrophy.py", line 7, in <module>
    from OpenElectrophy.gui.mainwindow import MainWindow
  File "/home/kjbrown/projects/OpenElectrophy/OpenElectrophy/gui/mainwindow.py", line 13, in <module>
    from guiutil.icons import icons
  File "/home/kjbrown/projects/OpenElectrophy/OpenElectrophy/gui/guiutil/__init__.py", line 6, in <module>
    from myguidata import *
  File "/home/kjbrown/projects/OpenElectrophy/OpenElectrophy/gui/guiutil/myguidata.py", line 5, in <module>
    from guidata.dataset.datatypes import DataSet 
  File "/home/kjbrown/miniconda/envs/openelectrophy/lib/python2.7/site-packages/guidata/__init__.py", line 541, in <module>
    import guidata.config
  File "/home/kjbrown/miniconda/envs/openelectrophy/lib/python2.7/site-packages/guidata/config.py", line 15, in <module>
    from guidata.configtools import add_image_module_path, get_translation
  File "/home/kjbrown/miniconda/envs/openelectrophy/lib/python2.7/site-packages/guidata/configtools.py", line 22, in <module>
    from guidata.qt.QtGui import (QFont, QLabel, QPixmap, QIcon, QHBoxLayout,
  File "/home/kjbrown/miniconda/envs/openelectrophy/lib/python2.7/site-packages/guidata/qt/__init__.py", line 25, in <module>
    sip.setapi('QString', 2)
ValueError: API 'QString' has already been set to version 1
````

**Comment by lepmik** [comment]
Hi, I've also had this issue, it got fixed when installing guidata from source: https://github.com/pierreraybaut/guidata, but I still dont understand why it occurs

Best

Mikkel

**Comment by cchorn** [comment]
I installed this from source.
It does not work for me. 
... still the same error
ValueError: API 'QString' has already been set to version 1

**Comment by lepmik** [comment]
This might sound strange, but on one occasion I had to first install guidata from source and then reinstall OE..
