### ISSUE TITLE
error spikesorting on sqlite db with neohdf5 loaded file

### ISSUE THREAD

**Issue by lepmik** [OpenElectrophy/OpenElectrophy#17]
Hi, I get this error when trying to spikesort from gui (right click on recordingchannelgroup) in a sqlite db with a neohdf5 file loaded. The neohdf5 file is capable of spikesorting when opened as read only file with neo.

```python
recompute_cluster_center
Traceback (most recent call last):
  File "/home/mikkel/apps/AnalysisPipeline/dependencies/OpenElectrophy/OpenElectrophy/gui/qtsqltreeview.py", line 439, in callContextMenu
    m.execute( **kargs)
  File "/home/mikkel/apps/AnalysisPipeline/dependencies/OpenElectrophy/OpenElectrophy/gui/contextmenu.py", line 266, in execute
    w= SpikeSortingWindow(spikesorter = spikesorter, session = session, dbinfo = treedescription.dbinfo, settings =settings)
  File "/home/mikkel/apps/AnalysisPipeline/dependencies/OpenElectrophy/OpenElectrophy/gui/spikesorting/spikesortingwindow.py", line 109, in __init__
    w = W( spikesorter = self.spikesorter ,settings = self.settings )
  File "/home/mikkel/apps/AnalysisPipeline/dependencies/OpenElectrophy/OpenElectrophy/gui/spikesorting/signals.py", line 100, in __init__
    self.time_by_seg[s]= sps.segs[s].analogsignals[0].t_start.magnitude
IndexError: list index out of range
```

**Comment by lepmik** [comment]
I get the same error if I try to spikesort on a neohdf5 file without any analogsignals - do you think time_by_seg could be set in any other way?
